project:
  type: website
  output-dir: docs

website:
  title: "Reasoning"
  site-url: https://shixiangwang.github.io
  description: "Reasoning is a blog dedicated to exploring the intersection of data science, bioinformatics, and personal insights."
  page-navigation: true
  twitter-card:
    creator: "@WangShxiang"
    card-style: summary_large_image
  navbar:
    left:
      - text: Resources
        #file: resource.qmd
        menu:
          - text: Code and Books
            file: resource.qmd
    right:
    # https://icons.getbootstrap.com/ for icon list
      - text: Resume
        href: https://shixiangwang.github.io/cv-shixiang/
      - icon: wechat
        href: https://shixiangwang.github.io/home/logo/qrcode.jpg
      - icon: quora
        href: https://www.zhihu.com/people/shixiangwang
      - icon: github
        href: https://github.com/ShixiangWang
      - icon: twitter
        href: https://twitter.com/WangShxiang
      - icon: rss
        href: index.xml
  page-footer:
    left: "Blog made with 💜 and [Quarto](https://quarto.org/), by Shixiang Wang. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/shixiangwang/
      - icon: twitter
        href: https://twitter.com/WangShxiang
      - icon: envelope
        href: mailto:shixiang1994wang@gmail.com
      - icon: rss
        href: index.xml
format:
  html:
    theme: morph
    css: styles.css
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    include-in-header: meta.html
    toc: true
    code-link: true

comments:
  giscus:
    repo: shixiangwang/shixiangwang.github.io

