baseurl: "https://shixiangwang.github.io/"
publishDir: "docs"
RelativeURLs: true
languageCode: "en-us"
title: "Shixiang Wang"
theme: "hugo-prose"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
paginate: 2

permalinks:
  post: "/post/:year/:month/:day/:slug/"

outputs:
  home: [html, rss, json]

# some menu items were added via the `menu` option in YAML in posts
menu:
  header:
    - name: Search
      url: "#"
      identifier: menu-search
    - name: Subscribe
      url: "index.xml"
  footer:
    - name: Contact
      url: "/404.html"
      weight: 1
    - name: Categories
      url: "/categories/"
      weight: 2
      pre: "optional"
    - name: Tags
      url: "/tags/"
      weight: 3
      pre: "optional"
    - name: Suggest an edit
      url: "#"
      weight: 4
      identifier: "menu-edit"
    - name: Back to top
      url: "#"

params:
  homePosts: 6
  mainSections: ["post", "work"]
  editLink: "https://github.com/shixiangwang/shixiangwang.github.io/edit/master/content/"
  authorDelimiter: " / "
  pageFeatures: [+sidenotes]
  description: >
    A website built through Hugo and blogdown with the hugo-prose theme.
  footer: >
    &copy; [Shixiang Wang](https://github.com/shixiangwang)
    2021 -- Present
  license: >
    Text and figures are licensed under [Creative Commons Attribution CC BY
    4.0](https://creativecommons.org/licenses/by/4.0/). The source code is
    licensed under MIT. The full source is available at
    https://github.com/shixiangwang/shixiangwang.github.io.

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
