---
title: 从 Faker 夺冠讨论竞争与热爱
author: Shixiang Wang
date: 2023-11-21
categories: [thought]
draft: false
description: ''

toc: true

format:
  html:
    code-fold: false
    code-overflow: wrap
    code-tools: false
---

好的想法需要记录，在这里动笔前，昨天睡前的好想法差点从指缝中溜走。

---

Faker，闪耀英雄联盟十年的职业选手，带领 T1 再次登上王座。
这是他的第 4 座世界赛冠军奖杯，但他离上一次登顶已经过去很多年了。
想要回忆，都已经得翻过我人生几千天的篇章。在那个懵懂和充满斗气的年代，
他也是青涩，却以高超的技巧以魔王的姿态统治了游戏中的王朝。

但他又再次登顶了，当众多英雄折戟沉沙、黯然退出，为什么他还在坚持？
为什么在沦入尘沙时坚持，为什么在近年当千年老二坚持？奶奶对他说，
要做便做到最好。他早已做到最好，为什么还在坚持？

我思考了很久。只有热爱，才能解释。

在越加竞争的世界里，我曾以为科研工作是一个宁静的港湾，但很显然，飓风已成，一切都将被席卷。
当资源的博奕无法避免，个人而言，躺平是最下层的解法。
为什么今年的比赛 Faker 带领的 T1 能够把把将 LPL 战队击穿，如人机一般？
我在一个知乎的帖子里看到了最认同的解析：[“不惧强度对抗”](https://www.zhihu.com/question/630835967/answer/3294626092)。
「不怕摩擦，不怕双方接触，寻求双方对抗。」在对抗中寻找战机和赛果。

未战先怯，败亡之道。

这狠狠地击中了我近年的“科研心态”。个人独立独行时，我们天然地寻求庇护之所，以求遮风挡雨、得以存活。
我们把对思想的追求降低到对生活的满足，就此沉沦。工作/事业，绝不会因为你把它当作一份工作而出色，它只会
因为你的热爱，你灌注的思想情绪而出彩。

固然，世界，特别是周遭的环境变化太大、压力太巨，但追求之心、努力之行不该有所松懈。不要让任何的标签定义，不要让任何的时间限制，不要让任何的思想束缚，一步一步、锤炼再锤炼、博弈再博弈。

与天斗，其乐无穷；与地斗，其乐无穷；与人斗，其乐无穷。

