---
title: 冷门的追求 - 书摘
author: Shixiang Wang
date: 2024-11-22
categories: [journal, academic, note]
draft: false
description: ''

toc: true

format:
  html:
    code-fold: false
    code-overflow: wrap
    code-tools: false
---

今天无意中通过知乎看到一篇非常引入入胜的演讲文章，从题目到内容都发人深省，难得的是，这是1981年的观点，我却觉得丝毫不过时。未免记忆和资料丢失，我这里人工搬运到自己的网站，以后有机会再多看看，警惕自身、塑造远见。

以下是引文（来源：<https://txyyss.wordpress.com/2024/11/07/unfashionable-pursuits/>）：

*** 

何夕的科幻小说《伤心者》在科幻迷心目中享有盛誉，但里面描写的毕竟是虚构的人物和故事。而 1981 年 8 月 24 日在亚历山大-洪堡基金会与新泽西州普林斯顿高等研究院合作举办的洪堡获奖者两国座谈会上，弗里曼·戴森（Freeman J. Dyson）发表了题为 Unfashionable Pursuits 的演讲。感谢现代科技，我们现在仍然可以[听到他的演讲](https://umedia.lib.umn.edu/item/p16022coll171:3633)。在我看来，这篇演讲稿举的例子胜过《伤心者》里的主人公，因为那都是真实发生过的。而演讲的主旨在于号召独立的科研机构向冷门的科学有所倾斜，如果确实照此实践下去，会大大降低《伤心者》里悲剧发生的可能性。

我想办法找到了演讲稿，在 ChatGPT 的帮助下把它翻译成了中文，并对照原文做了修改使得翻译更加准确。

## 引言

我很高兴今天能作为高等研究院的代表，向洪堡基金会的校友们致辞，因为高等研究院和洪堡基金会都在致力于国际层面的科学支持，并面临着相似的困境和挑战。我们都在延续亚历山大·冯·洪堡在 150 年前建立的传统。为了了解洪堡的贡献，我查阅了 1910 年第十一版《不列颠百科全书》，找到了科学史学家艾格尼丝·克拉克撰写的精彩文章。如果查阅的是百科全书的后续版本，克拉克的描述就只剩些零散的片段了。在文章中，她描述了洪堡在创建第一个国际气象和磁场观测站网络方面的工作，并以这样一句振奋人心的话作为结尾：“因此，现代文明最崇高的成果之一——国家间的科学联合，首次通过他的努力得以成功组织起来。”这正是我们所努力的方向：高等研究院和洪堡基金会，正在追随洪堡的优秀榜样，试图在我们这个时代加强和拓展国家间的科学合作。

## 科学中的潮流

我决定讨论科学中的“潮流”问题，因为这对整个科学界，特别是对高等研究院和洪堡基金会来说，是个日益重要的严肃问题。我将首先谈谈我们在高等研究院对这一问题的看法，然后谈谈我们可以从更长时间尺度的科学历史中学到的教训，最后我将简要讨论我们如何在未来更明智地应对这一问题。

对一位才能一般的年轻科学家来说，跟随大潮流是一条明智之路，这一事实自古以来如此，现在更是如此。任何没有非凡天赋或运气的年轻科学家，首先关心的是找到并保住一份工作。要找到并保住工作，你必须在那些控制就业市场的“权威”感兴趣的科学领域中做出合格的研究。而这些“权威”们认为有趣的科学问题，几乎就是我们所说的“热门”问题。如今，工作的分配通常由一组权威组成的委员会控制，委员会比个人更难脱离当下的流行趋势。因此，那些关心自身生存的年轻科学家往往会紧跟常规路径。那些高等学府提供了保障和提升机会给那些熟练追随潮流的人，而对于那些不追随潮流的人，机会则微乎其微。

我们的高等研究院也不例外。当我 34 年前第一次以访问成员身份来到这里时，主导的“权威”是罗伯特·奥本海默。他决定物理学的哪些领域值得追求。他的品味总是和最新的潮流一致。那时我年轻而有抱负，我向他提交了一篇快速完成的，涉及热门问题的工作，并因此获得了一份永久职位。这就是当时高等研究院的情况，现在依然如此。熟悉高等研究院历史的人可能会反驳说，毕竟高等研究院也给了库尔特·哥德尔一个永久职位。这确实是事实。哥德尔是我们这个世纪少数无可争议的天才之一，是唯一能与爱因斯坦平起平坐的同事。哥德尔从事的数学领域极其冷门，随着时间的推移，他的研究方向变得更加冷门。高等研究院有理由为他的加入而感到自豪。不过我们也必须承认一个事实：从哥德尔来到这里生活工作直到他成为教授，整整花了 14 年时间。哥德尔是如此独立且顽固，甚至可以说我们因为授予他教授头衔也值得一些肯定，尽管经过了 14 年的犹豫。迟做总比不做好。

今天来到高等研究院的年轻物理学家们，比 30 年前的我面临的压力要大得多。首先，他们大多数人带着政府合同资助而来，这些合同法律上要求他们在一定时间内从事某一特定科学领域的工作。当然，我们不会对合同的字面条款斤斤计较。国家科学基金会和能源部的合同管理人员是通情达理的人，他们允许我们在解释义务时有一定的灵活性。如果有些带合同资助的成员选择在与合同无关的领域工作，我们也不必把他们赶出门去。不符合合同资助内容的人员通常可以依靠研究院的资金支持。但是，合同仍然是一项严肃的限制。合同在总体上规定了高等研究院物理学院客座成员的工作领域，定义了物理学主流研究的方向。这也不可避免地影响了我们邀请的成员，他们的研究工作往往与某一合同内容相契合。

在工作了30年后，我现在已成为“权威”之一。我试图以一种模糊而微弱的方式，鼓励年轻物理学家在流行领域之外探索。我试图维持一些没有合同支持的研究领域。我希望保持这个研究院对独立和不合常规的精神开放，并为下一位像库尔特·哥德尔那样的人敞开大门。不过我必须承认，我对抗潮流的努力，效果大概就像我那著名的前辈克努特大抵试图阻挡大西洋潮水一样。如今，年轻人受到推动他们追随潮流的力量比合同的字面条款和“权威”的权力更为强大。驱使年轻人追逐热门领域的力量是同侪压力以及追逐的乐趣本身。他们知道“行动”在哪里，并渴望成为其中一部分。他们知道自己只有短暂的时间来证明自己。他们明白，想在有限的时间里取得成就，最佳的途径是随大流，去摘取那些已经成熟的科学果实。

年轻科学家们追求快速成功和回报本身并非坏事。将努力集中在流行的专业化领域并不一定有害。毕竟，这些流行问题之所以成为潮流，不是因为某个时尚设计师的随意决定，而是因为大多数科学家认为这些问题重要。通常，大多数人的判断是有依据的。流行的领域通常是产生重大发现的领域。年轻科学家进入这些领域，希望取得轰动性发现，这并没有错。事实上，研究院的日常生活正是因为流行领域的群体性研究而更加充实。当你在流行领域探索时，每一项小的成功和短暂的胜利都可以在午餐或研讨会上与朋友分享。如果没有这种对流行问题的共同兴趣，没有这种消息和传闻的分享，我们的生活会变得单调许多。

那么，为什么我不满？为什么我对年轻人做着我当年也做过的事情表示不满？我不满是因为我认为我们不应将所有的精力都放在流行的研究上。流行的研究有其用处，重要且令人兴奋。我们可以为年轻人专注于流行研究并取得成果而感到自豪。我们可以预见，他们中的大多数人总会出于我理解和尊重的原因，选择流行的研究方向。但我仅仅想说，我们这里也应当为那些不做流行研究的少数人提供空间。我们应当寻找并鼓励那些不符合主流模式的少数个体。我们应当在接纳成员时，稍微偏向那些不拘一格、不循常规的精神。如果我们不为从事非流行科学的人提供家园和工作空间，那么谁会呢？

## 古代历史

非流行科学的类型有很多种，支持这些科学的一个主要困难就是选择问题。非流行科学千姿百态，没有统一的结构。我来举一个例子。上周，我在普林斯顿大学的 Forrestal 校区散步时，看到两名研究生静静地坐在一片草地中央。起初我以为他们只是享受午后的阳光和宁静，但当我走近时，发现他们正全神贯注地进行一些需要稳健双手和不被打扰的精细操作。走近后，我看见他们正在忙着把小铅块粘在蜜蜂的背上。我默默地注视着他们，直到他们完成工作，然后与他们一起走回他们实验用的蜂巢，那是一个配备有相机和录像机的地方。他们正在改进并扩展卡尔·冯·弗里希关于蜜蜂舞蹈沟通系统的经典实验。他们发现，当蜜蜂找到离蜂巢较远的蜜源时，它们的舞蹈会更为激烈且精确。不幸的是，大多数蜜蜂会在靠近蜂巢处找到蜜源，返回时只会进行简短而随意的舞蹈。这些学生想要精确观察蜜蜂的舞蹈，于是他们找到了一种方法来诱使蜜蜂更为激烈地跳舞。背负 45 毫克铅块的蜜蜂会以为自己飞了很远的距离，尽管实际上只飞了很短的距离。蜜蜂通过飞行的努力程度来衡量飞行距离，因此负重的蜜蜂在每次找到蜜源后都会精确地跳舞。

这是非流行科学的一个典型例子，就在我们普林斯顿的门口进行着。我并不是建议高等研究院应该支持一个昆虫学学院。但这个蜜蜂实验的例子展示了非流行科学的所有特征：小规模、目标的多样性、个性化的风格以及某种表面上的不严肃性。

为了明确非流行科学的真正意义和持久价值，我回到我所擅长的领域，即数学物理。数学物理是试图通过纯数学的严谨风格和方法来深刻理解物理现象的学科。它位于物理学和数学的交界处。数学物理学家的目标不是定量地计算现象，而是定性地理解它们。他们用定理和证明进行研究，而不是用数字和计算机。他们的目标是通过数学上的精确性来阐明物理理论建立的概念的含义。

数学物理具有三个特点，使其在本次讨论中具有特别的相关性。首先，它在更大的图景中很重要，为物理学的更实用的领域提供基本的概念和词汇。其次，它发展缓慢，通常需要 50 到 100 年才能将一个新概念从起源发展到有效应用。第三，它几乎总是非流行的，因为它的发展节奏比科学潮流慢了大约 10 倍。由于它的非流行性，欧洲对它的重视和支持一直高于美国。

以一位对现代物理学发展至关重要的伟大数学物理学家为例，我想提到索菲斯·李（Sophus Lie）。李去世已有80年。他的主要工作是在 1870 年代到 1880 年代完成的，但他的思想直到最近 20 年才主导了粒子物理学家的思维。李是第一个理解并明确指出物理学原理具有群论起源的人。他几乎凭一己之力构建了一个庞大而美丽的连续群理论体系，他预见到它有朝一日会成为物理学的基础。现在，100 年后，每一位以对称性破缺和不破缺来分类粒子的物理学家，无论是否意识到，都在使用李的语言。然而，在他有生之年，李的思想却并不流行，数学家们对其理解甚少，物理学家更是完全不理解。费利克斯·克莱因是少数几个理解并支持他的著名数学家之一。

李是那些似乎总是运气不佳的人之一。1870 年，当普法战争爆发时，他正在法国四处游历。他是挪威人，但说法语时带有类似普鲁士口音的腔调。所以枫丹白露的爱国市民误认为他是普鲁士间谍，把他关进了监狱。与此同时，法国战败，形势变得愈加混乱。李静静地坐在牢房中，继续进行他的新数学发现，直到他的法国朋友们终于找到他所在的地方，成功将他释放出来。在出版于世纪之交的劳斯·鲍尔的数学史中，李的工作记录以一段哀伤的语调结尾：“李似乎因为自己的成果未得到普遍认可而感到失望和痛苦……他总是为自己所认为的对其成就的忽视而耿耿于怀，他生命最后十年的幸福也因此受到很大影响。”

另一位在他那个时代更加非流行的伟大数学物理学家是赫尔曼·格拉斯曼（Hermann Grassmann）。作为一名位于斯德丁的中学教师，他在 1844 年出版了一部名为《线性扩展理论》的作品，首次引入了向量、向量空间和非交换代数的基本概念。所有这些概念在 20 世纪的物理学中都具有核心地位，但在 19 世纪却不然。在他所处的世纪里，格拉斯曼始终是个默默无闻的中学教师，未被当时的学术权威们所重视。但他比索菲斯·李更具有韧性。格拉斯曼并未像李那样因未得到数学界的认可而怨天尤人，而是另辟蹊径，开始学习梵文，并以翻译《梨俱吠陀》为德语版获得了一定的声誉。或许，如果命运注定你是未被认可的数学天才，那么在中学教书生计比在大学任职对你的健康更有益。

在为这次会议准备发言时，我去高等研究院的图书馆，惊喜地发现那里保存着 1878 年版的《扩展理论》，封面上用铅笔写着爱因斯坦的导师、第一位理解相对论的数学家闵可夫斯基的名字。1878 年版有一篇格拉斯曼的序言，他仍在斯德丁，乐观地表达了希望这次新版能比 34 年前的首版更受学术界关注。在序言的结尾处，有一行脚注写道：“作者在印刷过程中去世”。直到 1890 年代，还是靠那位始终慷慨地为非流行的事业而战的费利克斯·克莱因，才促成了格拉斯曼的官方认可及其全集的出版。

另一个数学物理学领域的重要发现是规范场的概念，由赫尔曼·外尔（Hermann Weyl）于 1918 年提出。这个概念仅用了 50 年就成为现代粒子物理学的基本概念之一。量子色动力学，1981 年最流行的粒子物理学理论，在概念上无非是李群代数和外尔的规范场的结合。外尔的发现历史与李群和格拉斯曼代数的历史截然不同。外尔既不默默无闻，也未被忽视，他在 1918 年从事物理学中最时髦的领域，即新兴的广义相对论。他发明了规范场，作为统一引力和电磁学的解决方案。在短短几个月内，规范场理论登上了科学潮流的顶峰。然而，外尔和其他人很快发现，规范场并未达到预期的效果。规范场并未能实现外尔发明它的初衷，便迅速变得不再流行，几乎被遗忘。但在接下来的 50 年里，逐渐清楚的是，规范场在另一个不同背景下非常重要，尤其是在量子电动力学及量子色动力学的新近发展中得到了应用。普林斯顿的同事杨振宁和他的学生米尔斯于 1954 年，在外尔去世前一年，完成了规范场复兴的关键步骤。没有证据表明外尔知道或在意杨和米尔斯如何处理他的心血结晶。

关于规范场的历史充满了讽刺。一个为了实现短暂目的而被发明的热门概念，在经历了漫长的冷落期后，最终成为物理学的基石。在数学物理的悠久历史中，这样的讽刺并不少见。哈密顿发明的四元数，曾被誉为 19 世纪物理学问题的灵丹妙药，随后被弃之不用，却在 1920 年代的量子力学中以自旋矩阵的形式复活，如今又在 1980 年代的夸克场理论中登上巅峰。高斯发明的微分几何，最初是他在测地和制图工作中的副产品，50 年后被黎曼赋予抽象的通用形式，并成为爱因斯坦引力理论的概念基础。

这些故事中有几个共同点：一个是时间跨度，通常超过一个人的寿命长度；另一个是最终结果的完全不可预测性。发明关键概念的科学家几乎从未预见到这些概念在未来会被应用于何种物理背景。

讲述了这些历史例子之后，我认为已经足够证明我的观点：非流行的人和非流行的思想在科学进步中经常起着决定性的作用。我认为未来科学思想的发展模式不会与过去有太大不同。我们可以预见，在未来，非流行的思想将像过去一样，经过长时间的酝酿，甚至在意料之外的背景中浮现出重要性。作为科学进步的守护者，我们面临的问题是如何识别具有潜力的非流行思想，以及如何支持它们。

## 怪兽与教益

首先，我们可以环顾数学领域，看看是否能够识别出可能在 21 世纪成为物理学基本构件的非流行思想。如果幸运的话，我们可能会发现一些未来的优秀候选者。当然，我们在有生之年可能无法知道自己是否选择正确。

大致来说，非流行数学指的是那些被布尔巴基学派的权威视为非数学的部分。有一些非常美丽的数学发现属于这一类。根据布尔巴基的观点，要称之为数学，一个思想应具有普遍性、抽象性、连贯性，并与数学的其他部分通过清晰的逻辑关系相连。不属于数学的东西包括特定的事实、具体的对象，这些对象没有明显原因存在，可以说是偶然或零散的。非流行数学主要关注那些偶然的美，如特殊函数、特定的数域、例外代数、散在有限群。我建议你们在这些未组织和未受约束的数学领域中寻找下一次物理学革命的可能性。它们具有一种奇特、意外的特质，不容易融入布尔巴基的平滑逻辑结构中。正因为如此，我们应当珍惜并培养它们，记住弗朗西斯·培根的那句话，我们的院长哈里·伍尔夫在两年前的爱因斯坦百年纪念会上引用过：“没有哪一种绝佳的美在比例上没有一些奇怪之处”。

为了展示这种在比例上奇特的例子，我将简要谈谈散在有限群。它们的历史始于法国数学家埃米尔·马蒂厄（Émile Mathieu），他分别在 1861 年和 1873 年发现了第一和第二个散在群。马蒂厄，像此类发现的通常情况一样，并不知道他发明了散在群。事实上，“群”这个词甚至没有出现在他的论文标题中。但他清楚地知道自己发现了某种美丽且重要的东西。用几何语言来说，他发现了在 12 维和 24 维空间中存在一种特殊的对称性，这种对称性在其他维度的空间中不会出现。他的工作发表了出来，但在接下来的 100 年中依然不受欢迎，正如正统数学家喜欢说的那样，是一个“孤立的珍奇”，没有任何后续发展。

大约 75 年后，马蒂厄群在编码设计中显示出某种实用重要性。每一个马蒂厄群都构成了一个独特高效的纠错码的基础。然而，这种世俗的实用性并未提升马蒂厄群在那些由布尔巴基培养的数学家眼中的地位。

随后在过去的 20 年中，一批新的壮丽的散在群被不同的数学家通过各种方法发现了。其中一些数学家沿用了马蒂厄的思想，另一些则研究了 24 维空间中如何尽可能紧密地填充台球，还有一些人通过大计算机进行排列组合的测试来发现这些群。

这些发现的唯一共同点就是它们都具有具体、经验性、试验性、偶然的特征，完全与布尔巴基学派的精神相悖。总共发现了 25 个散在群，包括马蒂厄群在内。同时，使用更普遍和抽象方法的专业群论学者们成功地证明了散在群的总数不可能超过 26 个。因此，到了两年前，只有一个散在群尚未被发现。我们知道，如果这个群存在，它将是所有群中最大且最美的。追踪这个群的数学家们称其为“怪兽”或“友善的巨人”。

故事的结尾发生在去年，当时来自密歇根大学的鲍勃·格里斯（Bob Griess）在高等研究院访问期间，成功构造了“怪兽群”。昨天，我刚刚从密歇根收到了一份长篇论文的最终部分，详细记录了他的工作。怪兽群现在以其所有的光辉展现在那些愿意深入理解鲍勃·格里斯构造细节的人们面前。作为最后且最伟大的散在群，它将永远屹立不倒，犹如比青铜更持久的纪念碑。

这与物理学有什么关系呢？可能完全没有关系。可能散在群仅仅是数学史中的一段愉快的插曲，是一段远离主流进展的小故事。我们从未见过任何迹象表明物理宇宙的对称性与散在群的对称性有任何关联。就我们所知，物理宇宙的样子和功能，不会因散在群的存在或不存在而有所不同。但我们不应过于确信没有关联。证据的缺失并不等同于缺失的证据。在物理学史上，发生过比散在群意外出现更令人惊讶的事情。我们应当始终做好迎接意外的准备。我必须坦白地说，我心中怀有一个微弱的希望——这个希望并没有任何事实或证据支持——希望在 21 世纪的某个时刻，物理学家们会发现怪兽群以某种未被察觉的方式嵌入了宇宙结构中。当然，这只是一个天马行空的猜测，几乎肯定是错误的。我唯一能为此提供的理由是神学上的。我们有充分的证据表明，宇宙的创造者热爱对称性，而如果他热爱对称性，还有什么比怪兽群的对称性更美丽的呢？

散在群只是非流行数学宝库中奇妙且精彩概念的一个例子。我还可以提到其他许多例子。你能想象一个正多面体，即由完美对称的面以完美对称的结构组成的立体，其总共有11个面吗？去年，我的朋友唐纳德·考克斯特（Donald Coxeter）在多伦多发现了它。是否可能 zeta 函数的零点——其性质由黎曼 120 年前提出了猜想，至今仍然是数学的核心奥秘之一——会与物理世界有隐藏的关联？去年，贝尔实验室的数学家安德鲁·奥德利兹科（Andrew Odlyzko）使用一台 Cray 计算机，发现了 zeta 函数零点的一些新奇且意想不到的性质。是否可能库尔特·哥德尔的不完全性定理，证明了在任何给定的有限公理集和推理规则下，存在一些纯数学问题无法回答，未来能让我们更深入地理解物理宇宙知识的局限？无论你在思想的哪个领域观察，总会发现尚未揭示的启示暗示了即将到来的奥秘，隐藏的关联悄然低语。

但现在我的时间快到了，我必须兑现给大家一些关于科学支持的实际建议的承诺。我想对高等研究院和洪堡基金会说，作为独立机构，我们有义务也有特权，比政府的目光更为长远。我们的角色应当是以比政治家或博士后所能承担的更长远的视角来看待科学。这些故事告诉了我们什么教训？教训很简单。我们应当给予非流行研究更多的关注和支持。在科学史的任何一个特定时刻，最重要和最富有成果的思想往往因为不流行而处于休眠状态。尤其是在数学物理中，一个新思想的诞生到其融入科学主流之间通常会有 50 至 100 年的滞后期。如果这是根本性进步的时间尺度，那么可以推断，任何进行数学物理学基础工作的研究几乎注定是非流行的。

当然，我们不应停止支持那些让大多数年轻科学家忙碌且快乐的流行研究。但是我们应该拿出一部分资源——或许是十分之一，也或许是四分之一——来支持那些做非流行研究的人。我们不应害怕显得愚蠢甚至疯狂。我们不应害怕支持那些可能完全失败的冒险项目。既然我们是独立的机构，我们有权承担风险和犯错。那些只支持零风险、无错研究的组织最终只能支持平庸。如果我们能够以智慧和勇气支持那些正统观点认为无关紧要甚至疯狂的非流行人士，或许我们将为科学救出一位偶然的索菲斯·李或赫尔曼·格拉斯曼，他们的思想会在我们当代所有的流行兴奋点被遗忘很久之后，依然名扬四海。