---
title: dials自定义grid示例
author: 王诗翔
date: '2022-01-13'
slug: dials-grid
categories:
  - Blog
tags:
  - 机器学习
  - tidymodels
---

<!-- Links -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, warning = FALSE, message = FALSE,
  fig.width = 7, fig.height = 6
)
```

```{r}
library(dials)
library(dplyr)

param_quant =  function (label, range = c(10L, 1000L), type = "integer", trans = NULL) {
  stopifnot(length(label) == 1L)
  names(label) = label
  new_quant_param(type = type, range = range, 
                  inclusive = c(TRUE, TRUE),
                  trans = trans, label = label, 
                  finalize = NULL)
}

param_class =  function (label, values) {
  stopifnot(length(label) == 1L)
  names(label) = label
  new_qual_param(type = "character", values = values, label = label, 
                 finalize = NULL)
}

abc = grid_max_entropy(param_quant("scale"),
                       param_quant("abc", range = c(0, 1), trans = scales::log10_trans()),
                       param_class("gender", c("F", "M")),
                       size = 100, original = FALSE)
```

```{r}
plot(abc$scale, abc$abc)
```


