---
title: scRNA-seq_online 00：包准备
author: Shixiang Wang
date: 2023-05-31
categories: [bioinformatics,scRNA-seq]
draft: false
description: ''

toc: true

format:
  html:
    code-fold: false
    code-overflow: wrap
    code-tools: false
---

> 参考资料：<https://hbctraining.github.io/scRNA-seq_online/>

## 安装包

安装 CRAN 包：

```r
install.packages("BiocManager")
BiocManager::install(c("tidyverse", "Matrix", "RCurl", "scales", "cowplot", "Seurat", "metap"))
```

安装 Bioc 包：

```r
# options(BioC_mirror="https://mirrors.tuna.tsinghua.edu.cn/bioconductor")
BiocManager::install(c("AnnotationHub", "ensembldb", "multtest", "glmGamPoi"))
```

## 测试包的安装

```{r, collapse=TRUE}
library(Seurat)
library(tidyverse)
library(Matrix)
library(RCurl)
library(scales)
library(cowplot)
library(AnnotationHub)
library(ensembldb)
```

## 查看会话信息

```{r}
sessionInfo()
```


## 阅读

接下来就可以阅读以下两份非常好的材料了解单细胞的预备知识。

- [Introduction to single-cell RNA-seq](https://hbctraining.github.io/scRNA-seq_online/lessons/01_intro_to_scRNA-seq.html)
- [Generation of count matrix](https://hbctraining.github.io/scRNA-seq_online/lessons/02_SC_generation_of_count_matrix.html)


