---
title: random
author: Shixiang Wang
date: 2026-01-10
categories: [journal, AI]
draft: false
description: ''

toc: true

format:
  html:
    code-fold: false
    code-overflow: wrap
    code-tools: false
---

昨天用AI生成音乐，让AI以一首之前写的小诗改编，再去生成，简单一两轮对话，十分钟就生成了一首我个人听起来不错的歌。实在是太惊艳了。感觉2026年AI会在它触手能及，工业界盈利和兴趣能及的所有行业和生活场景中有大的突破，像水电一样嵌入人类社会。在科学方面，虽然比不上日常生活场景，私以为也会有类似的突破和规模效应，可能自己科研大部分工作被取代的可能性在未来两三年内很高，三五年普通研究人员指挥智能体和机器人进行计算实证研究的课题会变得可行可用。


AI生成音乐《我们这座城市》：

<https://i.y.qq.com/v8/playsong.html?songid=632785621#webchat_redirect>

阳光混着氧气填满这座城

和世界上千万座城没什么不同

看得见的光缠着看不见的空

喂饱了城里人潮的梦

百万千万数字背后藏着谁的痛

我们像蚂蚁筑着高楼的缝

也像蚂蚁忙着却像过客的风

我们单纯地想活着就像

想在黑暗甬道找到下一扇窗

可还是跟着路牌往前闯

不由自主被人潮推上那节车厢

毫无畏惧开往下一个黑地方

前进啊像列车擦着铁轨响

我们和城市撞啊撞融啊融

到最后分不清它是青春还是我们的样

霓虹混着尘埃落满这条路

和地图上千万条路没什么出路

握得住的票根缠着握不住的苦

撑着日子一天天重复

早班晚班钟摆背后藏着谁的孤独

我们像齿轮咬着明天的雾

也像齿轮转着却像停摆的钟鼓

我们用力地想活着就像

想在茫茫人海抓住一根稻草

可还是跟着人群往前跑

身不由己被时间卷进那座人潮

毫无犹豫挤向下一个老地方

坚持啊像陀螺转着不肯投降

我们和城市磨啊磨耗啊耗

到最后才发现它是伤疤也是我们的家

我们用青春砌着城市的墙

城市用回忆埋着我们的伤

我们用梦想换着三餐的汤

城市用灯火照着我们的慌

毫无畏惧开往下一个黑地方

前进啊像列车擦着铁轨响

我们和城市撞啊撞融啊融

到最后分不清它是青春还是我们的样

毫无犹豫挤向下一个老地方

坚持啊像陀螺转着不肯投降

我们和城市磨啊磨耗啊耗

到最后才发现它是伤疤也是我们的家