---
title: Bizard 项目成员招募与说明
author: Shixiang Wang
date: 2025-03-19
categories: [Bizard]
draft: false
description: ''

toc: true

format:
  html:
    code-fold: false
    code-overflow: wrap
    code-tools: false
---

前几天，我们正式官宣了「[Bizard（白泽）：生物医学可视化开源图鉴——一个社区项目的招募与探索](https://mp.weixin.qq.com/s/WtcxNFB0NyyZDv0UWhDFcw)」，引发了一些反响，许多朋友和粉丝进行了分享转发，有的朋友提供了项目方向的宝贵建议，有的小伙伴提出了参与的想法，我们也初步邀请了一些老师和公众号参与。这篇推文的目的是就上次未尽之处加以说明，另外也诚挚地邀请符合要求的老师/同学积极参与贡献。

## 项目内容与初步目标

项目的初步目标是建立一个基于R的可视化知识库，大体分为3大类：basics, omics, clinics，每类下面按不同的图形绘制分为中英文版本，中英文会在官方网站显示，中文会不断通过公众号推送更新；并不断根据想法和意见迭代更新，基本满足以后生物医学领域研究者的需求（未来也可以作为大语言模型的可靠知识基础）。

## 贡献方式设计

招募参与者的工作主要集中在图文教程的撰写和更新补充，其他事务主要由发起人及其学生团队负责，以保障项目的可靠运行。

因此，我们未来考虑系统化梳理需要处理的图文教程，参与者也可以参与补充和设计，然后以自由任务的形式下发通知项目成员，成员根据自己的兴趣、时间安排领取任务和进行处理。
针对一些参与者没有申领的任务，我们也会通过学生团队进行处理完成。

其他包括但不仅限于以下一些贡献类型：提供有效评论/建议；完成图文翻译任务；完成公众号推文编辑审核；提供重要指导意见；负责网站运维更新；负责贡献记录更新；负责推文运维更新。后面几类任务当前考虑由学生团队负责，以更好保证项目推进。

## 贡献记录机制

大概以一年为一个周期，记录参与创作者的贡献信息，按**积分制**。积分规则每年根据项目发起人和负责人商量确定。贡献者记录按「GitHub/微信ID/姓名」进行标注。贡献排名靠前者投稿时经讨论纳入共同第一作者，贡献排名靠后者经讨论纳入参与作者或致谢。如果长期提供指导性意见的贡献者经讨论纳入共同通讯作者。在对外宣传和文档记录时，积分排序也将作为主要参考依据。

「提供有效评论/建议」不仅限于项目参与者，在网站/公众号文章下方留言，我们觉得有意就会针对性加分统计！

## 我们期待这样的参与者

1. 有一定的时间（至少平均每周愿意投入1-2小时）并对该项目有兴趣。
2. 开源、共享、协作精神和意识。
3. 掌握 R 可视化与编程；有长期输出R及可视化博客/公众号经历 优先。

## 联系方式

- 罗鹏（<luopeng@smu.edu.cn>）
- 王诗翔（<wangshx@csu.edu.cn>）或通过「生信协作组」公众号后台交流添加老师微信，说明下参与 Bizard 项目


感谢！请大家多支持！
