---
title: 我记得
author: Shixiang Wang
date: 2024-11-11
categories: [journal]
draft: false
description: ''

toc: true

format:
  html:
    code-fold: false
    code-overflow: wrap
    code-tools: false
---

记忆是那么不牢固，我们一辈子又深陷其中，它追溯到我们来的时候，去往我们不可预知又必然而然的终点。

我越来越觉得，世界上美的东西，是难以描述和述说的，那是种主观的感受和体验。真正重要的文字和言语，是对这种体验的启发。

来去的意义、学习的意义、工作的意义、生活的意义、安稳的意义、名利的意义，有时候在我的脑海中时沉时浮，它们是“意义”，也是“活着”的目的和证明，但真正能代表我们这一生的痕迹吗？

在寻找工作，填写项目时，我一遍又一遍填写我的简历内容，好像生平已经被这些一两百字的描述吸收殆尽，我突然有一种惶恐，世人有可能会从这些文字中了解我吗？就如同我小时学习的那些诗人生平一般？

死亡，真是一种阴影！

***

<iframe width="560" height="315" src="https://www.youtube.com/embed/MmMvMF3ZC4o?si=Ct79YECsfQYotj6R" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


***

>《我记得》歌词

我带着比身体重的行李

游入尼罗河底

经过几道闪电 看到一堆光圈

不确定是不是这里

我看到几个人站在一起

他们拿着剪刀摘走我的行李

擦拭我的脑袋 没有机会返回去

直到我听见一个声音 我确定是你

可你怎记得我

我带来了另界的消息

可我怎么告知你

注定失忆着相遇

我记得这里是片树林 后面有个山坡

山坡上的枣树每当秋天到来

我们把枣装满口袋

我记得除了朋友我还 做过你的叔父

你总喜欢跟在我的屁股后面

只是为了那几个铜钱

我记得我们曾是恋人 后来战争爆发

你上战场后就再也没有回来

直到收不到你的信

我们总这样重复分离 却要重新开始

相互送别对方 说着来世再见

再次失忆着相聚

呜 呜 呜 呜

快来抱抱 快来抱抱我

呜 呜 呜 呜

快来抱抱 快来抱抱我

呜 呜 呜 呜

快来抱抱 快来抱抱我

呜 呜 呜 呜

快来抱抱 快来抱抱我

在路上我遇到了一位故去多年的人

她是如此年轻 扎着过肩马尾

露出和你一样的笑

她和我讲了很多关于你成长的故事

在星空另一端 思念从未停止

如同墓碑上的名字

不要哭我最亲爱的人 我最好的玩伴

时空是个圆圈 直行或是转弯

我们最终都会相见

在城池的某个拐角处 在夕阳西下时

在万家灯火的某一扇窗纱里

人们失忆着相聚

呜 快来抱抱 快来抱抱我

呜 快来抱抱 快来抱抱我

我终于找到你