---
title: 诗歌存档
author: Shixiang Wang
date: 2023-12-12
categories: [诗]
draft: false
description: ''

toc: true

format:
  html:
    code-fold: false
    code-overflow: wrap
    code-tools: false
---

存档下研究生期间写的一些诗，主要从[简书](https://www.jianshu.com/nb/8047834)搬运过来。大抵作于16年底到19年初。

<center>

### 电梯

楼上的人想下来

楼下的人想上去

在电梯门口相遇

奔往不同的去处



夜深了

众人归寝

他似从未闪过你的眼窗

你也未曾入了他的梦

### 脑中住着一个恶魔

我终于发现——

我的脑中，住着一个

喋喋不休的恶魔

它巧妙地隐藏在

我思绪的背后，如此小心地

偷偷窥视着我的一切

以至于，二十二年的时光里

我毫无所知

它第一次出现踪迹时

我还小，还年轻

现在我知道，它一直

躲在我思绪的影子下

它的动作太快，我的上一个念头

才产生反应，它已经

没有了踪迹

我不知道我现在怎么发现了它

正如我知道它曾经有被我发现

啊，曼妙的思潮

涌过了时空的海洋

降临于我之身

贫瘠的文字和韵律般的诗词怎能描述

那与我共生的恶魔啊

闪烁的火花被语言粘附

怎能寻得来时的去处——

便是我同恶魔一起从天国降落之地

### 我们在追寻着什么

我们在追寻着什么

像夜空追寻黎明

像喧嚣追寻安静

厌倦着黑夜，又寻觅着孤寂

我们在追寻着什么

像群星围绕着明月

像鹤立在鸡群

突显着自立，又遮掩着卑微

我们在追寻着什么

像头仰望着星空

像脚觅着实地

怀揣着梦想，又难以飞起

我们在追寻着什么

像夸父追逐着金乌

像愚公搬弄着山石

愚昧地坚持，又诚恳地守望

我们在追寻着什么

像不甘坠在平凡

像生活归于平淡

追寻着什么，丢失了什么

### 蝶恋花（一）

枫叶落红蝉韵歇。一觉秋深，窗外风声烈。

柳色犹新珠露结，厌教人世轻离别。

故友但去音笑绝。有限心身，仍共年年月。

何必年光留且住，随风吹取三山去。

> 三山：古代神话，东方大海里有三座仙山，叫做蓬莱、方丈、瀛州


### 蝶恋花（二）

阅尽友朋难久聚。旧梦残痕，空落思如许。

相忆常叹别离苦，秋风日夜无头绪。

拟送相思明月处。时雨轻寒，无计留它住。

一树桂花香暗渡，楼高不见来时路。

### 夜行者

我是夜中行者，

在梦眠时入睡，

在梦醒时工作。



睡时我总爱睁着眼睛，

摆动身躯，频频顿首，

容易，不废气力。

讨厌的是有时没法，精神紧张就

只能收紧身形，端坐，

好一副可爱模样。



我爱工作，

我是夜行者，

我爱工作。

随意地逡巡，行走

走过四季，边走边

望星空，望远山，望

春的夜风抚柳，听

夏的蛙蝉相和成歌，闻

秋的桂树落香，触

冬的雪花融化，

——成了水

喔！这一年的四季。

喔！这夜的行者。

伟大的夜的行者，

我要唱歌，喔——

该死的长喉，却是个咽炎患者！



那就继续走吧，

等那梦眠时我便要睡去，如何

再赏这多情的四季，

再望情坚不移的夜空星辰。

啊，上天，不要

不要让我躺下——

让我继续走，前行！

我是夜的行者。

啊，不要——

一躺下，

满是空虚，脑中会传来

心里的声音。

### 疯子对傻子

你问，

你别问——

我从哪里来，

说得清

说的不清。



你念，

你别念——

我往何处去，

不改变

一直改变。



你笑，

你别笑——

我为何在这里，

人只道

初衷不复。



你哭，

你别哭——

昨梦明朝尽空，

恭喜我

已修成疯。

### 点绛唇 望潇湘

一夜春风，

河边吹绿柳多少？

数声啼鸟，

频传春芳晓。



才过春初，

却也春将老。

远山道，

清明芳草，

看取西天渺。

### 暮春早行

垂枝映絮柳，情多添为愁。

人生几回乐，微风绿春波。

### 清明·崇明

草木方始绿，时节入春深。

遥叹连天水，近寻众芳痕。

少小囿世面，老大拭喧尘。

泛舟江海上，愿为钓鱼翁。

### 春晨惊起

恍然大梦春秋去，

不知鸿雁南归来。

惊起一瞥门窗外，

楼下樱花倚春开。

### 湿落的花，你莫留恋

如果你不曾料想，

又岂会无端地渴望。

机械钟表上起了发条，

是它在循环——

还是你在旋转。



听四月的风声暗哑，

低摆抽绿的絮柳，

园间一夜绽满的樱花，

共着桃花，

被连雨摧残。



湿落一地的花啊，

你是樱花，还是桃花。

你原是渴望春雨滋润，

还是期待飞落前的旋转？

你也莫想，

落红化入春泥，

也莫贪恋，

这人间的风景。

四周有的是水泥，

不缺的是轮回的春季。

我在烟雨朦胧中写下了你，

也只是因为，

手里的机器，

比我拥有更多的感情。

### 夜中的诗人

光消匿醒目

夜于风中放歌

委身黑暗，或鲜明

你无须选择

选择打造的包袱

不必拿起，你

孤注一掷，不留退路



月是你的魂侣

天晴，或多雨

是一种姿态，只为

靠近她

再无忧伤，反复

你是？

躯壳里的空空

月亮之上的白白

空白，哦——

是你，夜中的诗人

心在跳，思想

在发烫

### 五月

一场大雨，或天晴

将四月的尾身摆弄

水与空气升起嘈杂的共舞

冲刷犹存春痕

垂降夏季的五月



温度骤击突来的灼感

掀起层层陈年的躯皮

燥热，或寒酷

一时体内沉浸

年年的感觉回归

在这个初来的夏日

记忆恍若齿轮

回拨过往的印记



真也是齿轮——

盘过一圈，忘记

是在拨后，或往前

也忘记，正站在

旧时开端的终点

### 如果风不再刮

如果风不再刮

雨将笔直地下

多少雨外的等待

一场雨中的花开



如果风不再刮

小草无声地艳羡

众木躯干的挺直

多少历史的沧桑

验证谁内心执着挺拔

谁人倒下



如果风不再刮

古道西风瘦马

笑成满纸黄沙

铮铮心怀

谁人来写

谁人来听

谁人来看

### 行走在五月的风雨中

五月的风雨初骤

敲打你灯下的身影清瘦

于飘零之中，绿叶登台

恍然一场离家的远游



乘风而上

随雨而下

风雨中的叶

风雨中的你



逢过春的花已鲜明

润着水的绿正斑驳

该骂这天的捉弄

该笑这云的情多

看天空放阴

你兀自犹豫着

行走在初夏的雨后

### 当思绪反复成河

我在寻找一个词语

砥砺思绪，寻找

一个开始，一句借口

寻找，不停地

要文艺，像那

像那悲伤逆流成河

唯美诗意

要洒脱，将会

悲喜均不沾

无言升落

可惜我最终也没找到

或许我也说不出口



一日一夜的二十四小时

八万六千四百秒，有些精准

当我的心跳敲过这时间

地球又绕过了八万里的路程

反复的起点，也是

反复的终点

无言的岁月，反复

我的思绪，反复

反反复复在过去的两万多个日子里

不觉成河

而我又该流向哪里呢

我的大海

我的思潮奔涌

却还没有走到大陆尽头

### 道化之花

他躺在床上

看海波上淫淫的细雨

窗外，有海岸

也有天空



怎样去塑造一幅画镜

我心想

在作者的故事里

在太宰的内心处



退潮的海水

释放对世界侵蚀的火焰

道化之花

在那个女人的身体上绽放，枯萎

是的，那个一同殉情的女人



谁知道是我将她杀死？

我的朋友，你们可知道

叶藏望向窗外

可别离我而去，我的朋友

### 那年七夕

梦里一度贪欢，推杯到天明。

风雨旧时已谙，何处寻真情？

倚马待，望流云，天蓝人痴云不停。

何似幼时观月，月在人无心！



空中百鸟低巡，小镇响雷鸣。

日照离人一群，有晴也无情。

枝折花残谁在意，最是愁煞少年心：

肯为新词把酿得的才学倾。



品得书中颜玉，词新意不新。

看罢太白诗行，千愁同古今。

读新词，写旧诗，一生伴我度悲兴。

万物莫不月似，当自负亏盈！



七夕一岁又至，泪多软语频。

长情更是短情，此山万年青！

自古世间少味趣，诗与佳人共追寻。

恰如我意不负长词不负卿。

> 又翻出了14年七夕写的诗，心中莫名伤感。不，不应称为莫名。相同的情绪总是会在心底的某个时间点发酵，撒播出愁绪的气味。
>
> 曾把青春看做一个年龄阶段的必然经历。但我已不清楚我现在是入了青春，还是已在青春之外。时间总是耦合经历，把成长的气息悄然掩盖，而其中横跨的岁月光景，似乎仅在海马区留下关联的模式，在偶然的联想中掀起朵朵的记忆之花，提示过去真的不复存在。说到底，我们都是时间的扫墓人。

### 昏梦游思

风似乎从海边刮来

轻轻地，绕过森林与高楼

柔柔地，轻抚垂柳与衣袖

我站在高楼，感受着

风正从海边拂来



暑热退散

天上的火球降为远景

由黄转红的光色

洗澄金日的余晖

把留有残温的美景

送将夜的君国



一只鸟儿不耐寂寞，啁啾

我猜想它不是在唱歌——

文字里早已写烂

求偶吧？身体往往

比灵魂更诚实



人儿又何尝耐得住啊，繁华的

闪耀着白光，黄光，霓虹光的千盏万盏

在夜兽的胃腔中游弋，呼吸

争夺尚未分解的残食

直到杯盘狼藉，独自蜷缩入梦

盼着，梦里也是这般美好的世界

一个只关于兽的世界

而我，早已化身成兽

### 踏莎行 端午至

夜色将阑，

黄鹂报晓，

树头绿叶如新袄。

浮光透尽室窗明，

群楼难掩晨辉袅。



芳草勃勃，

离乡渺渺，

手拨箬叶眉心挑。

佳节又至欲销魂，

频传故梦托家老。

### 听歌

旋律升起

音调深浅高低

交纵组合开始，美妙啊

我渴望下一段



心底有个相同的节奏

恍若红日升起

普照世界啊，音乐

要什么神佛



好像什么人要来了

或是正在走过

生活啊，人类

我呆立良久

心有所思

物皆物语

### 独自莫凭楼

夜塔拨紫月拨银，

远灯照，近蝉鸣。

斜窥小径少人行，

空余暗柳，

倚光落疏影。



不闻浦江远水流，

近悠悠，远断愁。

难悟人间有情眸，

唯有短叹，

独自莫凭楼。

### 失眠

躺着

凌晨三点

一点亮点

又一个三点

无眠......

我怕是病了

入骨的热潮裹挟

夜幕的深渊

靠近，一点

一点，又一点

在夏季的凌晨三点

### 通宵

我隐匿于黑暗

沉醉于思考的逻辑

寂静夜色里

指针划过零点的界限

在屏幕微芒中显露尖锐

我浑然不觉

思维在图影的脉搏间跳跃

奔跑、迷失

“黑夜给了我黑色的眼睛”

我用它影射光明

信息汹涌流动着

在闪耀RGB编码的颜色光影里

我无心睡眠

也无心失眠

### 寂寞诗

寂寞的人逢着寂寞的夜

等着同样寂寞的人

该是何等的寂寞？

寂寞上的寂寞

寂寞后的寂寞

寂寞里的寂寞

最终能够不寂寞？

有点寂寞

喜欢说挺寂寞

恐怕说好寂寞

说不出不寂寞

哦，寂寞


### 尘光

白天的时光里身处喧嚣

夜晚至深时终归安宁

这城市静卧后

掸去了多少尘光

我就要在这物心两安的时刻睡去时

远桥的车光恍惚闪过

尘光还在——

我侧脸望向门窗外的夜空

最后的一眼里——星光遮掩

也许它一往如常

### 夏末

阳光是无声的沉默

轻风在无言地相守

这温暖而清爽的夏末

几月的酷热退散

季节转向初秋时候

我在小河旁漫走

眼中的绿色

依垂在杨柳枝头

粼粼泛起的波光中

我又想起了你

我又想起了你

眼波里正泛起的湖光粼粼

依垂在柳梢的绿色

映着我在河边走过

### 我在风中听雨

我在风中听雨

在雨中闻风

在风雨中想你

回到室内时

风雨隔窗远去

恍如背景

灰白天际里

我轻轻将你放入心底

抬眼向西

所有方向

在一片迷离

### 我是真的爱你

我是真的爱你

不仅爱你的身体

也爱你的心

爱阳光照你时的明媚

也爱微风轻抚你时的温柔

我是真的爱你

愿解开所有物质的锁链

放下精神上的所有

远赴千里

只为将你拥入怀中

我是真的爱你

衷心地许下每一个承诺

又默默将它们守候，见证我们

走过以后所有的一年四季

春夏秋冬

### 爱你的心

时间抹不去

疾病带不走

别人拿不了

爱你的心

我爱的人呵

只有你能将它呵护

又能把它摧毁

好好对待它吧

它因你而坚强存在

也因你而软弱无助

### 立冬后

立冬成昨日，好风下眉秋。

懒起梳妆晚，对镜已白头。

### 如一

一边是想你的绵愁

一边是工作的烦忧

我望着窗外阴沉的上海

这已是第二个年头

慢道忧虑的日子终将过去

去了归来，频频回首

一边是遇你的欢喜

一边是成长的苦痛

我在冬日写下此诗时

岁月正努力奔往春季

诗中也努力与四季作一场别离

末尾刻下爱你的如一


### 认岁月

若寻岁月身，音容辨旧痕。

凭吊芳华易，健忘父母恩。

### 晨起怅然有感

一盏黎明一盏灯，一宿思绪梦难成。

只恨神州地高远，别后山河是故人。

### 我昨日逢着一条狗

我昨日逢着一条狗

我散步路过的时候

看到它透过窗户

正对着我咧嘴笑



狗什么时候学会笑的？

我心里惊讶得很——

居然跟人一样

皮肉拉扯，琢磨不透



可能是在问好吧

我点点头

倒是一条好狗

眼睛也闪着亮泽



今天我又想遇着它

却看到门口小孩杵着狗皮在耍

一身贼亮的毛

还有塌陷下去的笑

### 一场九百年的梦

我做了一场九百年的梦

旁人问我为何

我告诉他——

我自己感觉如此呀



我的感觉一向准确

九百年，不多不少

在那之前，老师叫我们——

用“一场”造个句子

正好不多不少，九百年

我睡了九百年

然后写了下来



他骂我不老实——

“你，你怎可能睡得这么久？”

我微笑摇摇头

指了指我的席位

牌子上写着——

“一场九百年的梦”

### 吃掉你

我已经饱了

胃口撑的满满

可是……

为什么心里还有欲望

想要吃掉你



春风有些安静

请感受我的呼吸——

亲爱的

在床上，在梦里

来吧，让我们

依靠彼此



不要沉醉这夜

亲爱的，

也不要悲恼这黑

我将你挽进心底

不管它

明月圆缺

窗外迷离

### 做梦

似假非假，似空非空。

如不醒来，未觉梦中。

### 去做梦

夜沸腾得厉害

在黑暗里熬煮着

摇晃的城市里

大地满是水泡

那惨白的

早已退避的月光

是往别处去了

还是正蜷缩养伤？

还是睡去吧——

去梦里吧

至少梦里，可能

有一个想象的太阳

### 24小时

工作、学习、吃饭与睡眠

这日常的四件事情

将一天的24小时分割

一大段、一大段、一小段、一大段

还有究竟有多少间隙

我说不清

我好像做了很多

在这一天天的24小时

在这一段段分割的时空里

但却好像乱了

心里血液喷薄的红线

将身躯一圈圈紧绕

24小时，又24小时

我看不见它的线头

也瞧不见它的去处

只感觉越来越紧

冒着火色的双眼

越来难以看清

24小时够了吗？

不够再上24小时。

我在畅想，也在回望

可悲的是，就这样

本来连续的生命里

我活成了不连续的自、己

### 我即将在这午后的阳光下睡去

我即将在这午后的阳光下睡去

面对门窗，背靠办公椅

黄白的光斜着倾洒

在栏杆处投下斑驳的灰影

侵袭宿舍的每一个方寸

也照亮着这容身的方寸

微闭的眼睛里

存着远方天空的片段

连续地播放着

是白芒白茫的记忆

一只难以呼唤其名的鸟

横着从中间飞过

叫着春天，催我睡去

### 我们这座城市

阳光混合氧气充斥这座城市

像世界上的其他一万座城市。

看的见的光与看不见的虚无和着

输送给这座城市人口养料。

百万，千万

寥寥字眼里埋葬人口下的生活：

我们精心得像蚂蚁构造这座城市，

也忙碌得像蚂蚁存在着却好像只是路过。

我们像单纯地渴望活着一样

渴望着黑暗甬道的下一个出口——

可是，我们依然按照路牌的指引

不自主地拥抱人流，涌入车厢

毫无畏惧地驶向又一个

又下一个黑暗的地方。

前进啊，

像与车轨一路摩擦前行的列车，

我们与这座城市碰撞相融，

直到分不清它是青春

还是它就是我们。

### 相交的平行线

我曾经以为，

两条平行直线不会相交，

但宇宙就是这样，

在视线的远方，

人生的某个拐点，

我们彼此开始交汇，

融合。

这是相对论的咒语——

它在一直在那里，

而我们一起在这里。

> 在欧氏几何中，在两条平行线中做一条直线AB，以直线AB为半径以逆时针方向做圆，然后以直线AB为半径以顺时针方向再做一个圆，从两个圆的交点做垂线CD垂直于直线AB，若CD与AB的角的角度是90度，则说明两条平行线不会相交。
>
> 但欧几里得不敢思考当两条平行线无限长时的情况.....
>
> 于是包括罗素、黎曼在内的科学家假设当两条平行线无限长时，他们会在无穷远处相交。（例如：在地球的球面上，就会发现，相互垂直于赤道的经线会相交于北极点和南极点。）后来，非欧几何和黎曼空间就诞生了，该成果给了爱因斯坦很大的启发．

### 2018-06-15

由来万夫勇，挟此生雄风。笑尽一杯酒，杀人都市中。

“剑术已成君把去，有蛟龙处斩蛟龙”。

### 探春

樱红在园绿在野，东君扶柳捧金蝶。

人间终把寒根断，三月花开好时节。

### 2019-04-05

自然的规律

真真伟大的造物

它从无声息地彰显

你不由分说地融入

物理学家用数学丈量它

而我，

于生活中感触

</center>